-- AUTHOR: SCOEY DERUS
-- DATE 11/25/25
-- DESCRIPTION - CREATION OF A RETAIL SALES DATABASE TO BE POPULATED WITH FAKE DATA PARTIALLY GENERATED BY AI AND CHARTED VIA MATPLOTLIB OR POWERBI

CREATE DATABASE IF NOT EXISTS `Retail Database`;
USE `Retail Database`;

DROP TABLE IF EXISTS `TransactionItems`;
DROP TABLE IF EXISTS `Transactions`;
DROP TABLE IF EXISTS `Branch`;
DROP TABLE IF EXISTS `Customer`;
DROP TABLE IF EXISTS `Product`;

CREATE TABLE `Branch` (
    `BranchID` INT(6) NOT NULL PRIMARY KEY,
    `Country` VARCHAR(255) NOT NULL,
    `State` VARCHAR(255) NOT NULL,
    `City` VARCHAR(255) NOT NULL,
    `Address` VARCHAR(255) NOT NULL,
    `ZIPCODE` VARCHAR(255) NOT NULL
);

CREATE TABLE `Customer` (
    `CustomerID` INT(11) NOT NULL AUTO_INCREMENT, -- Default starts at 1, anon sales will be CustomerID = 0
    `CustomerName` VARCHAR(255) DEFAULT NULL,   -- all fields will be default null except for CustomerID 0 if anon
    `PhoneNumber` VARCHAR(255) DEFAULT NULL,
    `Address` VARCHAR(255) DEFAULT NULL,
    `Email` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`CustomerID`)
);

SET SESSION sql_mode = "NO_AUTO_VALUE_ON_ZERO"; -- GUARANTEES ANON AS 0
INSERT INTO `Customer`(`CustomerID`,`CustomerName`) VALUES(0, "Anon");

CREATE TABLE `Product` (
    `ProductID` INT(11) NOT NULL AUTO_INCREMENT, -- Every new entry will just add to the last one
    `ProductName` VARCHAR(255) NOT NULL,
    `Description` VARCHAR(255) DEFAULT NULL,
    `Price` DECIMAL(19,4) DEFAULT 0.00,
    `Category` VARCHAR(255) DEFAULT 'MISC',
    `Brand` VARCHAR(255) DEFAULT NULL,
    `Weight` DECIMAL(19,4) DEFAULT 0.00,
    `Flavor` VARCHAR(255) DEFAULT NULL,
    `Grain` BOOLEAN NOT NULL DEFAULT FALSE, -- Default is 0, meaning by default a product is grain free
    `Material` VARCHAR(255) DEFAULT NULL,
    `Color` VARCHAR(255) DEFAULT NULL,
    `SubCategory` VARCHAR(255) DEFAULT NULL,
    `Cost of Goods` DECIMAL(19,4) DEFAULT 0.00,
    PRIMARY KEY (`ProductID`)
);

CREATE TABLE `Transactions` (
    `TransactionID` INT(11) NOT NULL AUTO_INCREMENT,
    `CustomerID` INT(11),
    `Date` DATETIME NOT NULL,
    `BranchID` INT(6) NOT NULL,
    `EmployeeID` INT(11) DEFAULT NULL,
    PRIMARY KEY (`TransactionID`, `Date`),
    FOREIGN KEY (`CustomerID`) REFERENCES `Customer` (`CustomerID`),
    FOREIGN KEY (`BranchID`) REFERENCES `Branch` (`BranchID`)
);

CREATE TABLE `TransactionItems` (
    `TransactionItemID` INT(11) NOT NULL AUTO_INCREMENT,
    `TransactionID` INT(11) NOT NULL,
    `SaleTotal` DECIMAL(19,4) NOT NULL,
    `UnitTotal` INT(6) NOT NULL,
    `ProductID` INT(11) NOT NULL,
    PRIMARY KEY (`TransactionItemID`),
    FOREIGN KEY (`ProductID`) REFERENCES `Product` (`ProductID`),
    FOREIGN KEY (`TransactionID`) REFERENCES `Transactions` (`TransactionID`)
);

CREATE TABLE `Employee` (
    `EmployeeID` INT(11) NOT NULL AUTO_INCREMENT,
    `ManagerID` INT(11) DEFAULT NULL,
    `BranchID` INT(6) NOT NULL,
    `EmployeeName` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`EmployeeID`),
    FOREIGN KEY (`BranchID`) REFERENCES `Branch` (`BranchID`),
    FOREIGN KEY (`ManagerID`) REFERENCES `Employee` (`EmployeeID`)
);