USE `Retail Database`;
-- REAL ADDRESSES FOR PUBLIC GOVERNMENT BUILDINGS IN EACH CITY, FOR THIS EXAMPLE THEY ARE THE "BRANCHES"
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0001,'United States','Illinois','Skokie','5127 Oakton Street','60077');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0002,'United States','Wisconsin','Waukesha','201 Delafield Street','53188');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0003,'United States','Illinois','Chicago','121 North LaSalle Street','60602');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0004,'United States','New York','Buffalo','65 Niagara Square','14202');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0005,'United States','Ohio','Dayton','101 West Third Street','45402');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0006,'United States','Indiana','Indianapolis','46 East Ohio Street','46204');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0007,'United States','Michigan','Detroit','2 Woodward Avenue','48226');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0008,'United States','Minnesota','St. Paul','15 Kellogg Boulevard West','55102');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0009,'United States','Indianda','Fort Wayne','200 E Berry Street','46802');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0010,'United States','Pennsylvania','Pittsburgh','414 Grant Street','15219');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0011,'United States','Iowa','Des Moines','400 Robert D. Ray Drive','50309');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0012,'United States','Kentucky','Owensboro','101 East 4th Street','42303');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0013,'United States','Wisconsin','Kenosha','1010 56th Street','53140');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0014,'United States','Missouri','St. Louis','1200 Market Street','63103');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0015,'United States','Illinois','Urbana','400 S Vine Street','61801');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0016,'United States','Michigan','Marquette','300 West Baraga Avenue','49855');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0017,'United States','Tennesee','Nashville','600 Murfreesboro Pike','37210');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0018,'United States','Ohio','Cleveland','601 Lakeside Avenue','44114');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0019,'United States','Iowa','Mason City','220 North Washington Avenue','50401');
INSERT INTO `Branch`(`BranchID`,`Country`,`State`,`City`,`Address`,`ZIPCODE`) VALUES (0020,'United States','Indiana','Evansville','420 Mulberry Street','47713');